# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [1]:
#Import your libraries
import numpy as np
import pandas as pd

# Introduction

In this lab, we will use two datasets. Both datasets contain variables that describe apps from the Google Play Store. We will use our knowledge in feature extraction to process these datasets and prepare them for the use of a ML algorithm.

# Challenge 1 - Loading and Extracting Features from the First Dataset

#### In this challenge, our goals are: 

* Exploring the dataset.
* Identify the columns with missing values.
* Either replacing the missing values in each column or drop the columns.
* Conver each column to the appropriate type.

#### The first dataset contains different information describing the apps. 

Load the dataset into the variable `google_play` in the cell below. The dataset is in the file `googleplaystore.csv`

In [2]:
data = pd.read_csv('/Users/Kakurebono/Documents/GitHub/lab-supervised-learning-feature-extraction/data/googleplaystore.csv')

#### Examine all variables and their types in the following cell

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [4]:
data.dtypes

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [5]:
data.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

#### Since this dataset only contains one numeric column, let's skip the `describe()` function and look at the first 5 rows using the `head()` function

In [6]:
data.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

#### We can see that there are a few columns that could be coerced to numeric.

Start with the reviews column. We can evaluate what value is causing this column to be of object type finding the non-numeric values in this column. To do this, we recall the `to_numeric()` function. With this function, we are able to coerce all non-numeric data to null. We can then use the `isnull()` function to subset our dataframe using the True/False column that this function generates.

In the cell below, transform the Reviews column to numeric and assign this new column to the variable `Reviews_numeric`. Make sure to coerce the errors.

In [7]:
data.isnull()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,False,False,False,False,False,False,False,False,False,False,False,False,False
10837,False,False,False,False,False,False,False,False,False,False,False,False,False
10838,False,False,True,False,False,False,False,False,False,False,False,False,False
10839,False,False,False,False,False,False,False,False,False,False,False,False,False
10840,False,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
data.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [9]:
data["Reviews_numeric"] = pd.to_numeric(data["Reviews"], errors='coerce')

In [10]:
data.dtypes

App                 object
Category            object
Rating             float64
Reviews             object
Size                object
Installs            object
Type                object
Price               object
Content Rating      object
Genres              object
Last Updated        object
Current Ver         object
Android Ver         object
Reviews_numeric    float64
dtype: object

In [11]:
Reviews_isnull = data["Reviews_numeric"].isnull()

Next, create a column containing True/False values using the `isnull()` function. Assign this column to the `Reviews_isnull` variable.

Finally, subset the `google_play` with `Reviews_isnull`. This should give you all the rows that contain non-numeric characters.

Your output should look like:

![Reviews_bool.png](../images/reviews-bool.png)

In [12]:
data[Reviews_isnull]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN,NaN

#### We see that Google Play is using a shorthand for millions. 

Let's write a function to transform this data.

Steps:

1. Create a function that returns the correct numeric values of *Reviews*.
1. Define a test string with `M` in the last character.
1. Test your function with the test string. Make sure your function works correctly. If not, modify your functions and test again.

In [13]:
# Your code here

def convert_string_to_numeric(s):
    """
    Convert a string value to numeric. If the last character of the string is `M`, obtain the 
    numeric part of the string, multiply it with 1,000,000, then return the result. Otherwise, 
    convert the string to numeric value and return the result.
    
    Args:
        s: The Reviews score in string format.

    Returns:
        The correct numeric value of the Reviews score.
    """
    
    if s.isnumeric == True:
        return float(s)
    elif s[-1] == 'M':
        return float(s[:-1])*1000000
    else:
        return np.NaN

test_string = '4.0M'

convert_string_to_numeric(test_string) == 4000000

True

The last step is to apply the function to the `Reviews` column in the following cell:

In [14]:
data["Reviews"] = data["Reviews"].apply(convert_string_to_numeric)

Check the non-numeric `Reviews` row again. It should have been fixed now and you should see:

![Reviews_bool_fixed.png](../images/reviews-bool-fixed.png)

In [15]:
data[Reviews_isnull]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3000000.0,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN,NaN

Also check the variable types of `google_play`. The `Reviews` column should be a `float64` type now.

In [16]:
data.dtypes

App                 object
Category            object
Rating             float64
Reviews            float64
Size                object
Installs            object
Type                object
Price               object
Content Rating      object
Genres              object
Last Updated        object
Current Ver         object
Android Ver         object
Reviews_numeric    float64
dtype: object

#### The next column we will look at is `Size`. We start by looking at all unique values in `Size`:

*Hint: use `unique()` ([documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.unique.html))*.

In [17]:
data['Size'].unique()

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M',
       '31M', '4.2M', '7.0M', '23M', '6.0M', '6.1M', '4.6M', '9.2M',
       '5.2M', '11M', '24M', 'Varies with device', '9.4M', '15M', '10M',
       '1.2M', '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k',
       '3.6M', '5.7M', '8.6M', '2.4M', '27M', '2.5M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '66M', '79k', '8.4M', '118k', '44M', '695k', '1.6M',
       '6.2M', '18k', '53M', '1.4M', '3.0M', '5.8M', '3.8M', '9.6M',
       '45M', '63M', '49M', '77M', '4.4M', '4.8M', '70M', '6.9M', '9.3M',
       '10.0M', '8.1M', '36M', '84M', '97M', '2.0M', '1.9M', '1.8M',
       '5.3M', '47M', '556k', '526k', '76M', '7.6M', '59M', '9.7M', '78M',
       '72M', '43M', '7.7M', '6.3M', '334k', '34M', '93M', '65M', '79M',
       '100M', '58M', '50M', '68M', '64M', '67M', '60M', '94M', '232k',
       '99M', '624k', '95M', '8.5k', '41k', '292k', '11k', '80M', '1.7M',
       '74M', '62M', '69M', '75M', '98M', '85M', '82M', '96M', '87M',
       '71M', '86M', '91M', '81M', '92M', '83M', '88M', '704k', '862k',
       '899k', '378k', '266k', '375k', '1.3M', '975k', '980k', '4.1M',
       '89M', '696k', '544k', '525k', '920k', '779k', '853k', '720k',
       '713k', '772k', '318k', '58k', '241k', '196k', '857k', '51k',
       '953k', '865k', '251k', '930k', '540k', '313k', '746k', '203k',
       '26k', '314k', '239k', '371k', '220k', '730k', '756k', '91k',
       '293k', '17k', '74k', '14k', '317k', '78k', '924k', '902k', '818k',
       '81k', '939k', '169k', '45k', '475k', '965k', '90M', '545k', '61k',
       '283k', '655k', '714k', '93k', '872k', '121k', '322k', '1.0M',
       '976k', '172k', '238k', '549k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '705k', '306k', '904k', '473k', '175k',
       '350k', '383k', '454k', '421k', '70k', '812k', '442k', '842k',
       '417k', '412k', '459k', '478k', '335k', '782k', '721k', '430k',
       '429k', '192k', '200k', '460k', '728k', '496k', '816k', '414k',
       '506k', '887k', '613k', '243k', '569k', '778k', '683k', '592k',
       '319k', '186k', '840k', '647k', '191k', '373k', '437k', '598k',
       '716k', '585k', '982k', '222k', '219k', '55k', '948k', '323k',
       '691k', '511k', '951k', '963k', '25k', '554k', '351k', '27k',
       '82k', '208k', '913k', '514k', '551k', '29k', '103k', '898k',
       '743k', '116k', '153k', '209k', '353k', '499k', '173k', '597k',
       '809k', '122k', '411k', '400k', '801k', '787k', '237k', '50k',
       '643k', '986k', '97k', '516k', '837k', '780k', '961k', '269k',
       '20k', '498k', '600k', '749k', '642k', '881k', '72k', '656k',
       '601k', '221k', '228k', '108k', '940k', '176k', '33k', '663k',
       '34k', '942k', '259k', '164k', '458k', '245k', '629k', '28k',
       '288k', '775k', '785k', '636k', '916k', '994k', '309k', '485k',
       '914k', '903k', '608k', '500k', '54k', '562k', '847k', '957k',
       '688k', '811k', '270k', '48k', '329k', '523k', '921k', '874k',
       '981k', '784k', '280k', '24k', '518k', '754k', '892k', '154k',
       '860k', '364k', '387k', '626k', '161k', '879k', '39k', '970k',
       '170k', '141k', '160k', '144k', '143k', '190k', '376k', '193k',
       '246k', '73k', '658k', '992k', '253k', '420k', '404k', '1,000+',
       '470k', '226k', '240k', '89k', '234k', '257k', '861k', '467k',
       '157k', '44k', '676k', '67k', '552k', '885k', '1020k', '582k',
       '619k'], dtype=object)

You should have seen lots of unique values of the app sizes.

#### While we can convert most of the `Size` values to numeric in the same way we converted the `Reviews` values, there is one value that is impossible to convert.

What is that badass value? Enter it in the next cell and calculate the proportion of its occurence to the total number of records of `google_play`.

In [18]:
def convert_string_to_numeric(s):

    
    if s.isnumeric == True:
        return float(s)
    elif s[-1] == 'k':
        return float(s[:-1])*1000
    elif s[-1] == 'M':
        return float(s[:-1])*1000000
    else:
        return np.NaN

In [19]:
data["Size_numeric"] = data["Size"].apply(convert_string_to_numeric)

In [20]:
data[data['Size_numeric'].isnull()]['Size'].unique()

array(['Varies with device', '1,000+'], dtype=object)

#### While this column may be useful for other types of analysis, we opt to drop it from our dataset. 

There are two reasons. First, the majority of the data are ordinal but a sizeable proportion are missing because we cannot convert them to numerical values. Ordinal data are both numerical and categorical, and they usually can be ranked (e.g. 82k is smaller than 91M). In contrast, non-ordinal categorical data such as blood type and eye color cannot be ranked. The second reason is as a categorical column, it has too many unique values to produce meaningful insights. Therefore, in our case the simplest strategy would be to drop the column.

Drop the column in the cell below (use `inplace=True`)

In [21]:
data.drop(columns = ['Size_numeric', 'Size'], axis = 1, inplace = True)

#### Now let's look at how many missing values are in each column. 

This will give us an idea of whether we should come up with a missing data strategy or give up on the column all together. In the next column, find the number of missing values in each column: 

*Hint: use the `isna()` and `sum()` functions.*

In [22]:
data.isna().sum()

App                    0
Category               0
Rating              1474
Reviews            10840
Installs               0
Type                   1
Price                  0
Content Rating         1
Genres                 0
Last Updated           0
Current Ver            8
Android Ver            3
Reviews_numeric        1
dtype: int64

You should find the column with the most missing values is now `Rating`.

#### What is the proportion of the missing values in `Rating` to the total number of records?

Enter your answer in the cell below.

In [23]:
print((data['Rating'].isna().sum()/len(data))*100,'% missing values')

13.596531685268886 % missing values

A sizeable proportion of the `Rating` column is missing. A few other columns also contain several missing values.

#### We opt to preserve these columns and remove the rows containing missing data.

In particular, we don't want to drop the `Rating` column because:

* It is one of the most important columns in our dataset. 

* Since the dataset is not a time series, the loss of these rows will not have a negative impact on our ability to analyze the data. It will, however, cause us to lose some meaningful observations. But the loss is limited compared to the gain we receive by preserving these columns.

In the cell below, remove all rows containing at least one missing value. Use the `dropna()` function ([documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.dropna.html)). Assign the new dataframe to the variable `google_missing_removed`.

In [24]:
# Your code here:
pd.options.mode.chained_assignment = None

In [29]:
google_missing_removed = data.dropna()

In [30]:
google_missing_removed.head()

''' seems like that I am dropping all data for some reason''''

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver, Reviews_numeric]
Index: []

In [27]:
data

,App,Category,Rating,Reviews,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,NaN,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,159.0
1,Coloring book moana,ART_AND_DESIGN,3.9,NaN,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,967.0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,NaN,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,87510.0
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,NaN,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,215644.0
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,NaN,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,967.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,NaN,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up,38.0
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,NaN,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up,4.0
10838,Parkinson Exercices FR,MEDICAL,NaN,NaN,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up,3.0
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,NaN,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device,114.0
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,NaN,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device,398307.0

From now on, we use the `google_missing_removed` variable instead of `google_play`.

#### Next, we look at the `Last Updated` column.

The `Last Updated` column seems to contain a date, though it is classified as an object type. Let's convert this column using the `pd.to_datetime` function ([documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.to_datetime.html)).

In [28]:
google_missing_removed['Last Updated'] = pd.to_datetime(google_missing_removed['Last Updated'])

ParserError: day is out of range for month: 1.0.19

In [ ]:
google_missing_removed

#### The last column we will transform is `Price`. 

We start by looking at the unique values of this column.

In [ ]:
# Your code here:

Since all prices are ordinal data without exceptions, we can tranform this column by removing the dollar sign and converting to numeric. We can create a new column called `Price Numerical` and drop the original column.

We will achieve our goal in three steps. Follow the instructions of each step below.

#### First we remove the dollar sign. Do this in the next cell by applying the `str.replace` function to the column to replace `$` with an empty string (`''`).

In [ ]:
# Your code here:

#### Second step, coerce the `Price Numerical` column to numeric.

In [ ]:
# Your code here:

**Finally, drop the original `Price` column.**

In [ ]:
# Your code here:

Now check the variable types of `google_missing_removed`. Make sure:

* `Size` and `Price` columns have been removed.
* `Rating`, `Reviews`, and `Price Numerical` have the type of `float64`.
* `Last Updated` has the type of `datetime64`.

In [ ]:
# Your code here

# Challenge 2 - Loading and Extracting Features from the Second Dataset

Load the second dataset to the variable `google_reviews`. The data is in the file `googleplaystore_user_reviews.csv`.

In [32]:
google_reviews = pd.read_csv("/Users/Kakurebono/Documents/GitHub/lab-supervised-learning-feature-extraction/data/googleplaystore_user_reviews.csv")

#### This dataset contains the top 100 reviews for each app. 

Let's examine this dataset using the `head` function

In [33]:
google_reviews.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

#### The main piece of information we would like to extract from this dataset is the proportion of positive reviews of each app. 

Columns like `Sentiment_Polarity` and `Sentiment_Subjectivity` are not to our interests because we have no clue how to use them. We do not care about `Translated_Review` because natural language processing is too complex for us at present (in fact the `Sentiment`, `Sentiment_Polarity`, and `Sentiment_Subjectivity` columns are derived from `Translated_Review` the data scientists). 

What we care about in this challenge is `Sentiment`. To be more precise, we care about **what is the proportion of *Positive* sentiment of each app**. This will require us to aggregate the `Sentiment` data by `App` in order to calculate the proportions.

Now that you are clear about what we are trying to achieve, follow the steps below that will walk you through towards our goal.

#### Our first step will be to remove all rows with missing sentiment. 

In the next cell, drop all rows with missing data using the `dropna()` function and assign this new dataframe to `review_missing_removed`.

In [34]:
review_missing_removed = google_reviews.dropna()

#### Now, use the `value_counts()` function ([documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.value_counts.html)) to get a sense on how many apps are in this dataset and their review counts.

In [35]:
review_missing_removed['App'].unique()

array(['10 Best Foods for You', '104 找工作 - 找工作 找打工 找兼職 履歷健檢 履歷診療室',
       '11st', '1800 Contacts - Lens Store',
       '1LINE – One Line with One Touch',
       '2018Emoji Keyboard 😂 Emoticons Lite -sticker&gif',
       '21-Day Meditation Experience',
       '2Date Dating App, Love and matching',
       '2GIS: directory & navigator', '2RedBeans',
       '2ndLine - Second Phone Number',
       '30 Day Fitness Challenge - Workout at Home',
       '365Scores - Live Scores', '3D Live Neon Weed Launcher',
       '4 in a Row', '4K Wallpapers and Ultra HD Backgrounds',
       '591房屋交易-租屋、中古屋、新建案、實價登錄、別墅透天、公寓套房、捷運、買房賣房行情、房價房貸查詢', '591房屋交易-香港',
       '7 Cups: Anxiety & Stress Chat', '7 Day Food Journal Challenge',
       '7 Minute Workout', '7 Weeks - Habit & Goal Tracker',
       '8 Ball Pool', '850 Sports News Digest',
       '8fit Workouts & Meal Planner', '95Live -SG#1 Live Streaming App',
       'A Call From Santa Claus!', 'A Word A Day',
       'A&E - Watch Full Episodes of TV Shows',
       'A+ Gallery - Photos & Videos', 'A+ Mobile',
       'ABC Kids - Tracing & Phonics', 'ABC News - US & World News',
       'ABC Preschool Free', 'ABCmouse.com',
       'AC - Tips & News for Android™', 'ACE Elite',
       'AD - Nieuws, Sport, Regio & Entertainment', 'AMC Theatres', 'ANA',
       'AOL - News, Mail & Video', 'AP Mobile - Breaking News',
       'APE Weather ( Live Forecast)',
       'APUS Launcher - Theme, Wallpaper, Hide Apps', 'ARY NEWS',
       'ARY NEWS URDU', 'ASOS', 'ASUS Calling Screen',
       'ASUS Cover for ZenFone 2', 'ASUS Quick Memo',
       'ASUS Sound Recorder', 'ASUS SuperNote',
       'AT&T Navigator: Maps, Traffic', 'AT&T Smart Wi-Fi',
       'AT&T Visual Voicemail',
       'AVG Cleaner – Speed, Battery & Memory Booster',
       'Abs Training-Burn belly fat', 'Account Manager',
       'Accounting App - Zoho Books',
       'AccuWeather: Daily Forecast & Live Weather Reports',
       'Acorn TV: World-class TV from Britain and Beyond',
       'Acorns - Invest Spare Change', 'AdWords Express',
       'Ada - Your Health Guide', 'Add Text To Photo',
       'Adobe Acrobat Reader',
       'Adobe Photoshop Express:Photo Editor Collage Maker',
       'Advanced Task Killer', 'Agar.io', 'Age Calculator',
       'Agoda – Hotel Booking Deals', 'Air Traffic', 'AirAsia',
       'AirBrush: Easy Photo Editor', 'Airbnb',
       'Airport + Flight Tracker Radar',
       'Airway Ex - Intubate. Anesthetize. Train.', 'Akinator',
       'AlReader -any text book reader', 'Alarm Clock',
       'Alarm Clock Free', 'Alfred Home Security Camera',
       'AliExpress - Smarter Shopping, Better Living',
       'All Email Providers', 'All Events in City',
       'All Football - Latest News & Videos',
       'All Football GO- Live Score, Games',
       'All Language Translator Free', 'All Maths Formulas',
       'All Mental disorders', 'All Social Networks',
       'All Video Downloader 2018',
       'All-In-One Toolbox: Cleaner, Booster, App Manager',
       'All-in-One Mahjong 3 FREE', 'Allegiant',
       'Allrecipes Dinner Spinner', "Alto's Adventure", 'Amazon Drive',
       'Amazon FreeTime – Kids’ Videos, Books, & TV shows',
       'Amazon Kindle', 'Amazon Prime Video', 'Amazon Shopping',
       'Amazon for Tablets', 'American Airlines', 'Amex Mobile',
       'Amino: Communities and Chats', 'Amtrak',
       'Anatomy Learning - 3D Atlas', 'Ancestry',
       'AndroZip™ FREE File Manager',
       'Android Auto - Maps, Media, Messaging & Voice',
       'Android Messages', 'Anger of stick 5 : zombie', 'Angry Birds 2',
       'Angry Birds Classic', 'Angry Birds Rio', 'Animal Planet GO',
       'Animated Photo Editor',
       'Anime Avatar Creator: Make Your Own Avatar',
       'Anime Manga Coloring Book', 'Anthem Anywhere',
       'Anthem BC Anywhere',
       'Any.do: To-do list, Calendar, Reminders & Planner',
       'Apartment Decorating Ideas',
       'Apartment List: Housing, Apt, and Property Rentals',
       'Apartment, Home Rental Search: Realtor.com Rentals',
       'Apartments & Rentals - Zillow', 'Apartments.com Rental Search',
       'Apex Launcher', 'Apk Installer', 'App vault', 'AppLock',
       'AppLock - Fingerprint', 'Apple Daily 蘋果動新聞',
       'Aprender inglés con Wlingua', 'Archos File Manager', 'Arrow.io',
       'Asana: organize team projects', 'Ascape VR: 360° Virtual Travel',
       'Asphalt 8: Airborne', 'Associated Credit Union Mobile',
       'Asteroids 3D live wallpaper',
       'Atlan3D Navigation: Korea navigator',
       'AutoCAD - DWG Viewer & Editor',
       'AutoScout24 Switzerland – Find your new car',
       'Avakin Life - 3D virtual world', 'Aviary Effects: Classic',
       'Aviary Stickers: Free Pack', 'Azar', 'Azpen eReader',
       'B612 - Beauty & Filter Camera', 'BBC Media Player', 'BBC News',
       'BBC Sport', 'BBM - Free Calls & Messages', 'BBVA Compass Banking',
       'BBVA Spain', 'BBW Dating & Curvy Singles Chat- LargeFriends',
       'BBW Dating & Plus Size Chat', 'BBWCupid - BBW Dating App',
       'BELONG Beating Cancer Together', 'BEST CAR SOUNDS',
       'BET NOW - Watch Shows', 'BEYBLADE BURST app', 'BIG Launcher',
       'BLK - Swipe. Match. Chat.', 'BZWBK24 mobile',
       'BaBe - Baca Berita', 'BaBe Lite - Baca Berita Hemat Kuota',
       'BaBe+ - Berita Indonesia', 'Babbel – Learn Languages',
       'Babbel – Learn Spanish',
       'Baby ABC in box! Kids alphabet games for toddlers!',
       'Baby Monitor', 'Baby Name Together', 'Baby Panda Care',
       'Baby Panda Learns Shapes', 'Baby Panda Musical Genius',
       'Baby Panda’s Juice Shop',
       'Baby Tiger Care - My Cute Virtual Pet Friend', 'Baby puzzles',
       'Baca- Berita Terbaru, Informasi, Gosip dan Politik',
       'Backgrounds (HD Wallpapers)', 'Backgrounds HD (Wallpapers)',
       'BaconReader for Reddit', 'Bad Piggies',
       'Badoo - Free Chat & Dating App', 'Bagan - Myanmar Keyboard',
       'Banco Itaú', 'Banco do Brasil', 'Bancomer móvil',
       'Banfield Pet Health Tracker', 'Bangla Newspaper – Prothom Alo',
       'Banjo', 'Bank of America Mobile Banking', 'BankMobile Vibe App',
       'Banorte Movil', 'Banque Populaire', 'Barbie Life™',
       'Barbie Magical Fashion', 'Barbie™ Fashion Closet',
       'Barclays US for Android', 'Barcode Scanner',
       'Baritastic - Bariatric Tracker', 'Baseball Boy!',
       'Basketball FRVR - Shoot the Hoop and Slam Dunk!',
       'Basketball Stars', 'Bathroom Decorating Ideas',
       'Battlelands Royale', 'Be A Legend: Soccer',
       'BeSoccer - Soccer Live Score', 'BeWild Free Dating & Chat App',
       'Beautiful Design Birthday Cake', 'Beautiful Widgets Free',
       'Beautiful Widgets Pro', 'Beauty Camera - Selfie Camera',
       'Beauty Makeup Snappy Collage Photo Editor - Lidow',
       'BeautyPlus - Easy Photo Editor & Selfie Camera',
       'Bed Time Fan - White Noise Sleep Sounds', 'Best Car Wallpapers',
       'Best Fiends - Free Puzzle Game',
       'Best Ovulation Tracker Fertility Calendar App Glow',
       'Best Wallpapers Backgrounds(100,000+ 4K HD)',
       'Best Wallpapers QHD',
       'BestCam Selfie-selfie, beauty camera, photo editor',
       'BetterMe: Weight Loss Workouts', 'Betterment',
       'BeyondMenu Food Delivery', 'BeyondPod Podcast Manager', 'Bible',
       'Big Days - Events Countdown',
       'BigOven Recipes, Meal Planner, Grocery List & More',
       'BiggerCity: Chat for gay bears, chubs & chasers',
       'Bike Computer - GPS Cycling Tracker', 'Binaural Beats Meditation',
       'Binaural Beats Therapy', 'BioLife Plasma Services',
       'Birdays – Birthday reminder',
       'Birds Sounds Ringtones & Wallpapers',
       'Black People Meet Singles Date', 'Block Puzzle',
       'Block Puzzle Classic Legend !', 'Blogaway for Android (Blogger)',
       'Blogger', "Bloglovin'", 'Blood Donor', 'Blood Pressure',
       'Blood Pressure Log - MyDiary', 'Blood Pressure(BP) Diary',
       'Bloomberg Professional', 'Bloomberg: Market & Financial News',
       'Blossom Blast Saga', 'BluTV', 'Blur Image Background',
       'Blur Image Background Editor (Blur Photo Editor)',
       'Booking.com Travel Deals', 'Bowmasters', 'Box', 'Boxed Wholesale',
       "Boys Photo Editor - Six Pack & Men's Suit",
       'Brain Waves - Binaural Beats', 'Branch',
       'Brasileirão Pro 2018 - Série A e B',
       'Breaking News, Local news, Attacks and Alerts Free',
       'Brightest Flashlight Free ®', 'Brightest LED Flashlight',
       'Brilliant', 'Brit + Co', 'British Airways', 'Browser 4G',
       'Bualuang mBanking', 'Bubble Shooter', 'Bubble Shooter 2',
       'Bubble Shooter Genies', 'Bubble Shooter Space',
       'Bubble Witch 3 Saga', 'Buienradar - weer', 'Build a Bridge!',
       'Bukalapak - Jual Beli Online', 'BukuBayi - Perkembangan Bayi',
       'Burner - Free Phone Number', 'Buscapé - Ofertas e descontos',
       'Business Calendar 2', 'Butterfly Live Wallpaper',
       'Buzz Launcher-Smart&Free Theme', 'BuzzFeed: News, Tasty, Quizzes',
       'BÁO MỚI - Đọc Báo, Tin Tức 24h', 'C Programming',
       'C++ Programming', 'C++ Tutorials', 'CAIXA',
       'CALCU™ Stylish Calculator Free', 'CATS: Crash Arena Turbo Stars',
       'CBS News', 'CBS Sports App - Scores, News, Stats & Watch Live',
       'CBS Sports Fantasy', 'CDL Practice Test 2018 Edition',
       'CIA - Caller ID & Call Blocker',
       'CM Browser - Ad Blocker , Fast Download , Privacy',
       'CM Flashlight (Compass, SOS)',
       'CM Launcher 3D - Theme, Wallpapers, Efficient',
       'CM Locker - Security Lockscreen', 'CMB Free Dating App',
       'CNBC: Breaking Business News & Live Market Data',
       'CNN Breaking US & World News', "COOKING MAMA Let's Cook!",
       'CVS Caremark', 'CW Seed', 'CWT To Go',
       'Cache Cleaner-DU Speed Booster (booster & cleaner)',
       'Caf - Mon Compte',
       'Calculator - free calculator, multi calculator app',
       'Calculator - unit converter', 'Calculator Plus Free',
       'Calculator with Percent (Free)', 'Calendar Widget Month + Agenda',
       'Calendar+ Schedule Planner App', 'Call Blocker',
       'Call Control - Call Blocker', 'Call of Duty:Black Ops Zombies',
       'CallApp: Caller ID, Blocker & Phone Call Recorder', 'Caller ID +',
       'Calls & Text by Mo+', 'Calls Blacklist - Call Blocker',
       'Calm - Meditate, Sleep, Relax', 'Calorie Counter & Diet Tracker',
       'Calorie Counter - EasyFit free', 'Calorie Counter - Macros',
       'Calorie Counter - MyFitnessPal', 'Calorie Counter - MyNetDiary',
       'Cameringo Lite. Filters Camera', 'Candy Bomb',
       'Candy Camera - selfie, beauty camera, photo editor',
       'Candy Crush Jelly Saga', 'Candy Crush Saga',
       'Candy Crush Soda Saga', 'Candy Day', 'Candy Pop Story',
       'Candy Smash', 'Candy selfie - photo editor, live filter camera',
       'Canva: Poster, banner, card maker & graphic design',
       'Canvas Student', 'Cat Sim Online: Play with Cats',
       'Caviar - Food Delivery', 'Chakra Cleansing', 'Championat',
       'Chapters: Interactive Stories', 'Chase Mobile',
       'Chat Rooms, Avatars, Date - Galaxy', 'ChatVideo Meet new people',
       'Cheap Flights & Hotels momondo',
       'Cheap hotel deals and discounts — Hotellook',
       'CheapTickets – Hotels, Flights & Travel Deals',
       'Cheapflights – Flight Search', 'CheckPoints 🏆 Rewards App',
       'Checkers ✔️', 'Checkout 51: Grocery coupons', 'Choice Hotels',
       'Choices: Stories You Play', 'Christian Dating For Free App',
       'Chrome Beta', 'Chrome Dev', 'Cinemark Theatres',
       'Cisco Webex Meetings', 'Cisco Webex Teams', 'Citi Mobile®',
       'Citibanamex Movil', 'Citizens Bank Mobile Banking',
       'CityMaps2Go Plan Trips Travel Guide Offline Maps', 'Claro',
       'Clash Royale', 'Clash of Clans', 'Color Flashlight', 'Color Road',
       'Color Touch Effects', 'Color by Number - Draw Sandbox Pixel Art',
       'Color by Number – New Coloring Book',
       'ColorFil - Adult Coloring Book', 'ColorNote Notepad Notes',
       'ColorSnap® Visualizer', 'Colorfit - Drawing & Coloring',
       'Colorful Glitter Neon Butterfly Keyboard Theme',
       'Colorfy: Coloring Book for Adults - Free', 'Coloring & Learn',
       'Coloring book moana', 'Comedy Central', 'Common Core',
       'Comptia A+ 220-901 & 220-902', 'ConnectLine', 'Contacts',
       'Contacts+', 'Content Transfer', 'ConvertPad - Unit Converter',
       'Cookbook Recipes', 'Cooking Channel', 'Cooking Fever',
       "Cooking Madness - A Chef's Restaurant Games", 'Cookpad',
       'Cool Popular Ringtones 2018 🔥', 'Cool Reader',
       'Couch to 10K Running Trainer', 'Couch to 5K by RunDouble',
       'Couchsurfing Travel App',
       'Cougar Dating Life : Date Older Women Sugar Mummy',
       'Couple - Relationship App', 'Credit Karma', 'Credit Sesame',
       'CreditWise from Capital One',
       'Crew - Free Messaging and Scheduling',
       'Cricbuzz - Live Cricket Scores & News',
       'Cricket Visual Voicemail', 'Crossy Road',
       'Crunchyroll - Everything Anime',
       'Current debit card and app made for teens',
       'Curriculum vitae App CV Builder Free Resume Maker',
       'Curso de Ingles Gratis', 'Cut the Rope 2',
       'Cut the Rope FULL FREE', 'Cycling - Bike Tracker',
       'Cymera Camera- Photo Editor, Filter,Collage,Layout',
       'Czech Public Transport IDOS', 'DC Comics', 'DC Super Hero Girls™',
       'DEAD TARGET: FPS Zombie Apocalypse Survival Games',
       'DEER HUNTER 2018', 'DELISH KITCHEN - 無料レシピ動画で料理を楽しく・簡単に！',
       'DINO HUNTER: DEADLY SHORES', 'DIY Garden Ideas',
       'DIY On A Budget', 'DMV Permit Practice Test 2018 Edition',
       'DRAGON BALL LEGENDS', 'DSLR Camera Hd Ultra Professional',
       'DStv Now', 'DU Browser—Browse fast & fun',
       'DU Recorder – Screen Recorder, Video Editor, Live',
       'Daily Workouts - Exercise Fitness Routine Trainer',
       'Daily Yoga - Yoga Fitness Plans',
       'Dailyhunt (Newshunt) - Latest News, Viral Videos', 'Dairy Queen',
       'Daniel Tiger for Parents', 'DashClock Widget',
       'Dashlane Free Password Manager',
       'Dating App, Flirt & Chat : W-Match',
       'Dating for 50 plus Mature Singles – FINALLY', 'Daum Mail - 다음 메일',
       "Davis's Drug Guide", "Davis's Drug Guide for Nurses",
       'Debonairs Pizza',
       'Delivery Club–Доставка еды:пицца,суши,бургер,салат',
       'Delta Dental', 'Despegar.com Hoteles y Vuelos',
       'Detector de Radares Gratis', 'Device Help',
       'Diabetes & Diet Tracker', 'Diabetes:M',
       'Diamond Zipper Lock Screen', 'Diary with lock',
       'Diary with lock password', 'Dictionary - Merriam-Webster',
       'Die TK-App – alles im Griff', 'Digg', 'DigiCal Calendar Agenda',
       'Digit Save Money Automatically', 'Digital Alarm Clock', 'Dil Mil',
       'Dino War: Rise of Beasts', 'Dinosaur Simulator: Dino World',
       'Discover Mobile', 'Disney Heroes: Battle Mode',
       'Disney Magic Kingdoms: Build Your Own Magical Park',
       'DisneyNOW – TV Shows & Games', 'Divar',
       'Do It Later: Tasks & To-Dos', 'Docs To Go™ Free Office Suite',
       'Doctor On Demand', 'Doctor Pets', 'Dog Licks Screen Wallpaper',
       'Dog Run - Pet Dog Simulator', 'Dog Sim Online: Raise a Family',
       "Domino's Pizza USA", 'Dominos Game ✔️',
       'Domofond Недвижимость. Купить, снять квартиру.', 'Doodle Jump',
       'Door Lock Screen', 'DoorDash - Food Delivery',
       'Dosecast - Medication Reminder', 'Down Dog: Great Yoga Anywhere',
       'Dr. Oetker Rezeptideen', "Dr. Panda & Toto's Treehouse",
       'Dr. Panda Restaurant 3', 'Dr. Panda Town: Vacation',
       'DraftKings - Daily Fantasy Sports', 'Dragon Hills',
       'Draw A Stickman', 'Draw In', 'Draw Your Game',
       'Draw a Stickman: EPIC 2',
       'Drawing for Kids Learning Games for Toddlers age 3',
       'Dream League Soccer 2018', 'DreamTrips', 'DreamWorks Friends',
       'Dresses Ideas & Fashions +3000', 'Droid Zap by Motorola',
       'DroidAdmin for Android - Advice', 'Dropbox',
       'Drugs.com Medication Guide', 'Dude Perfect 2',
       'Dumb Ways to Die 2: The Games',
       'Dungeon Hunter Champions: Epic Online Action RPG',
       "Dunkin' Donuts", 'Duolingo: Learn Languages Free', 'DuraSpeed',
       'E*TRADE Mobile', 'Easy - taxi, car, ridesharing',
       'Easy Hair Style Design', 'Easy Healthy Recipes',
       'Easy Installer - Apps On SD', 'Easy Makeup Tutorials',
       'Easy Origami Ideas', 'Easy Recipes', 'Easy Voice Recorder',
       'EasyBib: Citation Generator', 'Eat Fit - Diet and Health Free',
       'Eat24 Food Delivery & Takeout', 'EatStreet Food Delivery App',
       'Ebates: Cash Back, Coupons, Rewards & Savings', 'Ebook Reader',
       'Ecobank Mobile Banking', 'Edmodo', 'Educational Games 4 Kids',
       'Educational Games for Kids', 'El tiempo de AEMET',
       'English with Lingualeo', 'English-Myanmar Dictionary', 'Entel',
       'Enterprise Rent-A-Car', 'Episode - Choose Your Story',
       'Epocrates Plus', 'Equestria Girls', 'Essential Anatomy 3',
       'Essential Resources', 'Etsy: Handmade & Vintage Goods',
       'Etta Homes', 'Eurosport',
       'Eve Period Tracker - Love, Sex & Relationships App',
       'Even - organize your money, get paid early',
       'Evernote – Organizer, Planner for Notes & Memos', 'Evie Launcher',
       'ExDialer - Dialer & Contacts',
       'Expedia Hotels, Flights & Car Rental Travel Deals',
       'Expense IQ Money Manager', 'Experian - Free Credit Report',
       'Extreme Car Driving Simulator', 'Extreme Coupon Finder',
       'Extreme Match', 'Extreme Racing 2 - Real driving RC cars game!',
       'EyeCloud', 'EyeEm - Camera & Photo Filter', 'EzCalculator',
       'FBReader: Favorite Book Reader', 'FERZU - Furries Social Network',
       'FIFA - Tournaments, Soccer News & Live Scores',
       'FINAL FANTASY BRAVE EXVIUS', 'FOSSIL Q: DESIGN YOUR DIAL', 'FOX',
       'FOX NOW - On Demand & Live TV',
       'FOX Sports: Live Streaming, Scores & News',
       'FREEDOME VPN Unlimited anonymous Wifi Security',
       'FUN Keyboard – Emoji Keyboard, Sticker,Theme & GIF',
       'Fabulous: Motivate Me! Meditate, Relax, Sleep',
       'Face Filter, Selfie Editor - Sweet Camera', 'Facebook',
       'Facebook Ads Manager', 'Facebook Lite', 'Facebook Local',
       'Facebook Pages Manager', 'Facetune - Ad Free',
       'Fake Call - Fake Caller ID', 'Fallout Shelter',
       'Family Album Mitene: Private Photo & Video Sharing',
       'Family Dollar',
       'Family GPS Tracker and Chat + Baby Monitor Online',
       'Family GPS tracker KidControl + GPS by SMS Locator',
       'Family Locator - GPS Tracker', 'FamilySearch Tree',
       'FanDuel: Daily Fantasy Sports', 'Fancy Widgets',
       'Fandango Movies - Times + Tickets', 'Fantasy Football',
       'Fantasy Football & NFL News', 'Fantasy Football Manager (FPL)',
       'Farm Fruit Pop: Party Time', 'Farm Heroes Saga',
       'Farming Simulator 14', 'Farming Simulator 18', 'Fashion in Vogue',
       'Fast News', 'Fast Scanner : Free PDF Scan', 'Fast Secure VPN',
       'FastMeet: Chat, Dating, Love',
       'Fat Burning Workout - Home Weight lose',
       'Fate/Grand Order (English)',
       'FidMe Loyalty Cards & Deals at Grocery Supermarket',
       'File Browser by Astro (File Manager)', 'File Explorer',
       'File Manager',
       'File Manager -- Take Command of Your Files Easily',
       'Files Go by Google: Free up space on your phone',
       'FilterGrid - Cam&Photo Editor', 'Filters for B Live',
       'Filters for Selfie', 'Final Fantasy XV: A New Empire',
       'Financial Times', 'Find Dining Restaurant Finder',
       'Find a Way: Addictive Puzzle', 'Find&Save - Local Shopping',
       'FindShip', 'Firefox Browser fast & private',
       'Firefox Focus: The privacy browser', 'Fishdom', 'Fitbit',
       'Flashlight', 'Flashlight & LED Torch',
       'Flashlight - Torch LED Light', 'Flashlight HD LED', 'Flickr',
       'Flight & Hotel Booking App - ixigo',

#### Now the tough part comes. Let's plan how we will achieve our goal:

1. We will count the number of reviews that contain *Positive* in the `Sentiment` column.

1. We will create a new dataframe to contain the `App` name, the number of positive reviews, and the total number of reviews of each app.

1. We will then loop the new dataframe to calculate the postivie review portion of each app.

#### Step 1: Count the number of positive reviews.

In the following cell, write a function that takes a column and returns the number of times *Positive* appears in the column. 

*Hint: One option is to use the `np.where()` function ([documentation](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.where.html)).*

In [36]:
# Your code below

def positive_function(x):
    """
    Count how many times the string `Positive` appears in a column (exact string match).
    
    Args:
        x: data column
    
    Returns:
        The number of occurrences of `Positive` in the column data.
    """
    count = 0
    for item in x:
        if item ==  'Positive':
            count +=1
    return count

In [37]:
count_positive = positive_function(review_missing_removed['Sentiment'])

In [38]:
count_positive

23998

#### Step 2: Create a new dataframe to contain the `App` name, the number of positive reviews, and the total number of reviews of each app

We will group `review_missing_removed` by the `App` column, then aggregate the grouped dataframe on the number of positive reviews and the total review counts of each app. The result will be assigned to a new variable `google_agg`. Here is the ([documentation on how to achieve it](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.core.groupby.DataFrameGroupBy.agg.html)). Take a moment or two to read the documentation and google examples because it is pretty complex.

When you obtain `google_agg`, check its values to make sure it has an `App` column as its index as well as a `Positive` column and a `Total` column. Your output should look like:

![Positive Reviews Agg](../images/positive-review-agg.png)

*Hint: Use `positive_function` you created earlier as part of the param passed to the `agg()` function in order to aggregate the number of positive reviews.*

#### Bonus:

As of Pandas v0.23.4, you may opt to supply an array or an object to `agg()`. If you use the array param, you'll need to rename the columns so that their names are `Positive` and `Total`. Using the object param will allow you to create the aggregated columns with the desirable names without renaming them. However, you will probably encounter a warning indicating supplying an object to `agg()` will become outdated. It's up to you which way you will use. Try both ways out. Any way is fine as long as it works.

In [39]:
google_agg = pd.DataFrame()

In [40]:
google_agg['App'] = review_missing_removed['App'].unique()

In [41]:
google_agg['Positive'] = [positive_function(review_missing_removed[review_missing_removed['App'] == i]['Sentiment']) for i in google_agg['App']]
google_agg['Total'] = [len(review_missing_removed[review_missing_removed['App'] == i]['Sentiment']) for i in google_agg['App']]

Print the first 5 rows of `google_agg` to check it.

In [48]:
google_agg.head()

                                App  Positive Ratio
0             10 Best Foods for You        0.835052
1  104 找工作 - 找工作 找打工 找兼職 履歷健檢 履歷診療室        0.775000
2                              11st        0.589744
3        1800 Contacts - Lens Store        0.800000
4   1LINE – One Line with One Touch        0.710526

#### Add a derived column to `google_agg` that is the ratio of the `Positive` and the `Total` columns. Call this column `Positive Ratio`. 

Make sure to account for the case where the denominator is zero using the `np.where()` function.

In [44]:
google_agg['Positive Ratio'] = google_agg['Positive']/google_agg['Total']# Your code here:

#### Now drop the `Positive` and `Total` columns. Do this with `inplace=True`.

In [45]:
google_agg.drop(columns=['Positive', 'Total'], inplace=True)

Print the first 5 rows of `google_agg`. Your output should look like:

![Positive Reviews Agg](../images/positive-review-ratio.png)

In [47]:
google_agg.head()

                                App  Positive Ratio
0             10 Best Foods for You        0.835052
1  104 找工作 - 找工作 找打工 找兼職 履歷健檢 履歷診療室        0.775000
2                              11st        0.589744
3        1800 Contacts - Lens Store        0.800000
4   1LINE – One Line with One Touch        0.710526

# Challenge 3 - Join the Dataframes

In this part of the lab, we will join the two dataframes and obtain a dataframe that contains features we can use in our ML algorithm.

In the next cell, join the `google_missing_removed` dataframe with the `google_agg` dataframe on the `App` column. Assign this dataframe to the variable `google`.

In [ ]:
'''I cound't do this due to my problem in challenge 1 where the dropna() drops my entire dataframe and returns an empty one''''

google = google_missing_removed.join(google_agg.set_index('App'),on='App', how='inner')

#### Let's look at the final result using the `head()` function. Your final product should look like:

![Final Product](../images/google-final-head.png)

In [ ]:
# Your code here: